ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.1
errorCode = 0
warningCode = 0

[rule.chaincode-privacy-leakage-in-arg]
[rule.chaincode-privacy-leakage-in-br]
[rule.chaincode-privacy-leakage-in-ret]